git:
  depth: 1
branches:
  except:
  - "/(?i:appveyor)/"
language: c++
compiler:
- gcc
- clang
os: osx
osx_image: xcode9.2
env:
- MATRIX_EVAL="DYLD_LIBRARY_PATH=":/usr/local/lib"
before_install:
- mkdir -p config lib/rtmidi/config
- touch config/config.rpath lib/rtmidi/config/config.rpath
- eval "${MATRIX_EVAL}"
- if test "$TRAVIS_OS_NAME" = osx ; then rm -rf /usr/local/include/c++ ; fi
script:
- if test "$TRAVIS_OS_NAME" = osx ; then echo "DYLD_LIBRARY_PATH = $DYLD_LIBRARY_PATH"
  ; fi ;
- if test "$TRAVIS_OS_NAME" = osx ; then echo "DYLD_FALLBACK_FRAMEWORK_PATH = $DYLD_FALLBACK_FRAMEWORK_PATH"
  ; fi ;
- if test "$TRAVIS_OS_NAME" = osx ; then make install &&  make tests ; fi ;
- mkdir -p public/$CC
- if test "$TRAVIS_OS_NAME" = osx ; then cp dylibbundler public/$CC ; fi ;
deploy:
- provider: releases
  api_key:
    secure: zoo9cYmsDytF4QqiOVMZC0OttLyln+OtkYZ6Oj2qERS8FWqYboVxtQs1IPBq30+r9pkCSyWdD8GOKzjTd/Bzvh/289rbU0WHaafsJnfnSsyZtpJudtMn4s6DMekbZECMrcCfBOuZnUG6uqp2ywGulpJdPCh73UnbqEwq9lluT+IDXgouX+utGPgToXhEc+OZWh1pdQMxM+6VmfUBJsUatrfOnD20TCVKcQwlf/OcUkhmLZspOjCgrTBoVUyNJACsSiEKN41Bx7mXvRjm7+PiFZ+WVTamIoL/i37bSzpAjlYLUWjdS7yqT3BzQf75ABFwTKotB5JLn3Q+JrUTJYyKDvd5iryxBISVtjcdP+ECeZP/j8pHKQmWPtBffpNF1FlUhGr/ry1vn7qMOrnLyumdjWgLuIDCeZcU7avu/rh38l3zTCx7G8OWa1HEJ2TX6GdJi02x/PKmgeO+vmJtSKjp+IXt8ULy5QzE6fz3WNkHX4b/t0IsOmzyJCnlflEcQiirfn0XdAN9a52pobkuD/L401odQrLzTJ/WwXuJcrrgmHZIqay5kbOkTtY7XrawZsMk6Xx1W0rNoUeDDMUi5wJvhRkuusUnIkSiRv1oPci6FEFkYAR4PTS6otYlL6uIRnpcvzYFwSGwV7Rwubw142TQ+DR24T/ahxKsAA2lhJgq0s4=
  file_glob: true
  file: public:*
  on:
    repo: keinstein/macdylibbundler
    branch: deploy
    - provider: pages
      skip_cleanup: true
      local-dir: public
      branch:    gh-pages
      keep-history: true
      github-token: $GITHUB_TOKEN
      verbose: true
      on:
          branch: deploy
